In [99]:
import pandas as pd
import numpy as np


In [100]:
df=pd.read_csv("/content/titanic_dataset .csv")     #Loading daatset

**EDA**

In [101]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [103]:
df.shape

(891, 12)

In [104]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [105]:
df.drop(["PassengerId", "Name","SibSp","Parch","Ticket","Fare","Cabin","Embarked"], axis="columns",inplace=True)
df.head()

Survived  Pclass     Sex   Age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [106]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
dtype: int64

In [108]:

median_age=df['Age'].median()    #Handling missing values
df['Age']= df['Age'].fillna(median_age)


In [109]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
dtype: int64

In [110]:
df=pd.get_dummies(df)                        #Encoding

In [111]:
df.head()

Survived  Pclass   Age  Sex_female  Sex_male
0         0       3  22.0           0         1
1         1       1  38.0           1         0
2         1       3  26.0           1         0
3         1       1  35.0           1         0
4         0       3  35.0           0         1

In [112]:
x=df.drop('Survived',axis=1)    #diving feature variables and target
y=df['Survived']
print(x)
print(y)


     Pclass   Age  Sex_female  Sex_male
0         3  22.0           0         1
1         1  38.0           1         0
2         3  26.0           1         0
3         1  35.0           1         0
4         3  35.0           0         1
..      ...   ...         ...       ...
886       2  27.0           0         1
887       1  19.0           1         0
888       3  28.0           1         0
889       1  26.0           0         1
890       3  32.0           0         1

[891 rows x 4 columns]
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64


**Hold_out technique**

In [116]:
from sklearn.model_selection import train_test_split

In [117]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.3)

**KNN**

In [123]:

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5)

classifier.fit(x_train, y_train)


KNeighborsClassifier()

In [124]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)             #model prediction

In [125]:
score_KNN = classifier.score(x_test,y_test)
score_KNN

0.7649253731343284

In [126]:
from sklearn.metrics import accuracy_score


accuracy = accuracy_score(y_test, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 76.49 %.


**K-FOLD on KNN Model**


In [127]:
from sklearn.model_selection import KFold
Kfold_validator = KFold(10)
for train_index,test_index in Kfold_validator.split(x,y):
    print('training Index:',train_index)
    print('testng Index:',test_index)

training Index: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 33

In [128]:
from sklearn.model_selection import cross_val_score
cv_result= cross_val_score(classifier,x,y,cv=Kfold_validator)
cv_result


array([0.72222222, 0.80898876, 0.75280899, 0.82022472, 0.80898876,
       0.80898876, 0.7752809 , 0.75280899, 0.86516854, 0.76404494])

In [129]:
import numpy as np
np.mean(cv_result)

0.7879525593008738

**Stratified Kfold on KNN Model**

In [130]:
from sklearn.model_selection import StratifiedKFold

In [131]:
skfold_validator = StratifiedKFold(n_splits=10)

In [132]:
for train_index,test_index in skfold_validator.split(x,y):
    print('training Index:',train_index)
    print('testng Index:',test_index)

training Index: [ 82  84  85  88  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 33

In [133]:
from sklearn.model_selection import cross_val_score
cv_result= cross_val_score(classifier,x,y,cv=skfold_validator)
cv_result

array([0.78888889, 0.84269663, 0.73033708, 0.82022472, 0.78651685,
       0.82022472, 0.79775281, 0.7752809 , 0.84269663, 0.75280899])

In [134]:
import numpy as np
np.mean(cv_result)

0.7957428214731586

 **SVM Model**

In [156]:


from sklearn.svm import SVC
svc_model=SVC()
svc_model.fit(x_train , y_train)

SVC()

In [157]:
# Predicting the Test set results
y_pred = svc_model.predict(x_test)

In [158]:
from sklearn.metrics import accuracy_score


accuracy = accuracy_score(y_test, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 59.33 %.


In [159]:
score_svc = svc_model.score(x_test,y_test)
score_svc

0.5932835820895522

**KFold on SVM Model**

In [160]:
from sklearn.model_selection import KFold
Kfold_validator = KFold(10)
for train_index,test_index in Kfold_validator.split(x,y):
    print('training Index:',train_index)
    print('testng Index:',test_index)

training Index: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 33

In [161]:
from sklearn.model_selection import cross_val_score
cv_result= cross_val_score(svc_model,x,y,cv=Kfold_validator)
cv_result

array([0.55555556, 0.7752809 , 0.74157303, 0.50561798, 0.59550562,
       0.73033708, 0.57303371, 0.65168539, 0.7752809 , 0.68539326])

In [162]:
import numpy as np
np.mean(cv_result)

0.6589263420724096

**Stratified cross validation on svm**

In [163]:
from sklearn.model_selection import StratifiedKFold

In [165]:
from sklearn.model_selection import cross_val_score
cv_result= cross_val_score(svc_model,x,y,cv=skfold_validator)
cv_result

array([0.62222222, 0.65168539, 0.70786517, 0.66292135, 0.61797753,
       0.69662921, 0.65168539, 0.64044944, 0.71910112, 0.65168539])

In [ ]:
import numpy as np
np.mean(cv_result)

0.6554806491885143